// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ubestarfm_train_patch_cpp
Rcpp::List ubestarfm_train_patch_cpp(const Rcpp::NumericMatrix& fine_1, const Rcpp::NumericMatrix& fine_2, const Rcpp::NumericMatrix& coarse_1, const Rcpp::NumericMatrix& coarse_2, int row_start, int row_end, int col_start, int col_end, int window_radius, double threshold_1, double threshold_2);
RcppExport SEXP _ubESTARFM_ubestarfm_train_patch_cpp(SEXP fine_1SEXP, SEXP fine_2SEXP, SEXP coarse_1SEXP, SEXP coarse_2SEXP, SEXP row_startSEXP, SEXP row_endSEXP, SEXP col_startSEXP, SEXP col_endSEXP, SEXP window_radiusSEXP, SEXP threshold_1SEXP, SEXP threshold_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type fine_1(fine_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type fine_2(fine_2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coarse_1(coarse_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coarse_2(coarse_2SEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_end(row_endSEXP);
    Rcpp::traits::input_parameter< int >::type col_start(col_startSEXP);
    Rcpp::traits::input_parameter< int >::type col_end(col_endSEXP);
    Rcpp::traits::input_parameter< int >::type window_radius(window_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type threshold_1(threshold_1SEXP);
    Rcpp::traits::input_parameter< double >::type threshold_2(threshold_2SEXP);
    rcpp_result_gen = Rcpp::wrap(ubestarfm_train_patch_cpp(fine_1, fine_2, coarse_1, coarse_2, row_start, row_end, col_start, col_end, window_radius, threshold_1, threshold_2));
    return rcpp_result_gen;
END_RCPP
}
// ubestarfm_assemble_masks_cpp
Rcpp::RawVector ubestarfm_assemble_masks_cpp(const Rcpp::List& patch_results, int total_cells, int mask_bytes);
RcppExport SEXP _ubESTARFM_ubestarfm_assemble_masks_cpp(SEXP patch_resultsSEXP, SEXP total_cellsSEXP, SEXP mask_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type patch_results(patch_resultsSEXP);
    Rcpp::traits::input_parameter< int >::type total_cells(total_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type mask_bytes(mask_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(ubestarfm_assemble_masks_cpp(patch_results, total_cells, mask_bytes));
    return rcpp_result_gen;
END_RCPP
}
// ubestarfm_predict_patch_cpp
Rcpp::NumericMatrix ubestarfm_predict_patch_cpp(const Rcpp::NumericMatrix& fine_1, const Rcpp::NumericMatrix& fine_2, const Rcpp::NumericMatrix& coarse_1, const Rcpp::NumericMatrix& coarse_2, const Rcpp::RawVector& candidate_masks, int mask_bytes, const Rcpp::NumericVector& targets, int target_count, int row_start, int row_end, int col_start, int col_end, int window_radius, std::string method, double value_min, double value_max);
RcppExport SEXP _ubESTARFM_ubestarfm_predict_patch_cpp(SEXP fine_1SEXP, SEXP fine_2SEXP, SEXP coarse_1SEXP, SEXP coarse_2SEXP, SEXP candidate_masksSEXP, SEXP mask_bytesSEXP, SEXP targetsSEXP, SEXP target_countSEXP, SEXP row_startSEXP, SEXP row_endSEXP, SEXP col_startSEXP, SEXP col_endSEXP, SEXP window_radiusSEXP, SEXP methodSEXP, SEXP value_minSEXP, SEXP value_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type fine_1(fine_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type fine_2(fine_2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coarse_1(coarse_1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coarse_2(coarse_2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type candidate_masks(candidate_masksSEXP);
    Rcpp::traits::input_parameter< int >::type mask_bytes(mask_bytesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< int >::type target_count(target_countSEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_end(row_endSEXP);
    Rcpp::traits::input_parameter< int >::type col_start(col_startSEXP);
    Rcpp::traits::input_parameter< int >::type col_end(col_endSEXP);
    Rcpp::traits::input_parameter< int >::type window_radius(window_radiusSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type value_min(value_minSEXP);
    Rcpp::traits::input_parameter< double >::type value_max(value_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ubestarfm_predict_patch_cpp(fine_1, fine_2, coarse_1, coarse_2, candidate_masks, mask_bytes, targets, target_count, row_start, row_end, col_start, col_end, window_radius, method, value_min, value_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ubESTARFM_ubestarfm_train_patch_cpp", (DL_FUNC) &_ubESTARFM_ubestarfm_train_patch_cpp, 11},
    {"_ubESTARFM_ubestarfm_assemble_masks_cpp", (DL_FUNC) &_ubESTARFM_ubestarfm_assemble_masks_cpp, 3},
    {"_ubESTARFM_ubestarfm_predict_patch_cpp", (DL_FUNC) &_ubESTARFM_ubestarfm_predict_patch_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_ubESTARFM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
