# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ubestarfm_train_patch_cpp <- function(fine_1, fine_2, coarse_1, coarse_2, row_start, row_end, col_start, col_end, window_radius, threshold_1, threshold_2) {
    .Call(`_ubESTARFM_ubestarfm_train_patch_cpp`, fine_1, fine_2, coarse_1, coarse_2, row_start, row_end, col_start, col_end, window_radius, threshold_1, threshold_2)
}

ubestarfm_assemble_masks_cpp <- function(patch_results, total_cells, mask_bytes) {
    .Call(`_ubESTARFM_ubestarfm_assemble_masks_cpp`, patch_results, total_cells, mask_bytes)
}

